In [322]:
import numpy as np

In [323]:
#01.Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.

arr = np.array([1,7,13,105])
print(arr)
print(f"type = {type(arr)}")
print(f"Item Size = {arr.itemsize}")
print(f"Size = {arr.size}")

[  1   7  13 105]
type = <class 'numpy.ndarray'>
Item Size = 8
Size = 4


In [324]:
#02.Write a NumPy program to create an element-wise comparison (greater,    greater_equal, less and less_equal) of two given arrays.

arr = np.array([1,7,13,105])
arr1 = np.array([1,4,14,110])
print(arr)
print(arr1)
print("comparison-greater")
print(np.greater(arr,arr1))
print("comparison-greater_equal")
print(np.greater_equal(arr,arr1))
print("comparison-less")
print(np.less(arr,arr1))
print("comparison-less_equal")
print(np.less_equal(arr,arr1))

[  1   7  13 105]
[  1   4  14 110]
comparison-greater
[False  True False False]
comparison-greater_equal
[ True  True False False]
comparison-less
[False False  True  True]
comparison-less_equal
[ True False  True  True]


In [325]:
#03.Write a NumPy program to create an array of 10 zeros, 10 ones, 10    fives, 10 tens, 10 twentys and 10 fiftys.

arr2 = np.arange(0,11)
print(arr2)
arr2 = np.zeros(10)
print(arr2)
arr2 = np.ones(10)
print(arr2)
arr2 = np.ones(10)*5
print(arr2)
arr2 = np.ones(10)*10
print(arr2)
arr2 = np.ones(10)*20
print(arr2)
arr2 = np.ones(10)*50
print(arr2)

[ 0  1  2  3  4  5  6  7  8  9 10]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
[20. 20. 20. 20. 20. 20. 20. 20. 20. 20.]
[50. 50. 50. 50. 50. 50. 50. 50. 50. 50.]


In [326]:
#04.Write a NumPy program to create an array of integers from 30 to 70.

arr3 = np.arange(30,70)
print(arr3)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]


In [327]:
#05.Write a NumPy program to create an array of integers from 50 to 95.

arr4 = np.arange(50,95)
print(arr4)

[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94]


In [328]:
#06.Write a NumPy program to create an array of all even integers from 20 to 80.

arr5 = np.arange(20,80,2)
print(arr5)

[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66
 68 70 72 74 76 78]


In [329]:
#07.Write a NumPy program to create an array of all odd integers from 20 to 80.

arr6 = np.arange(21,80,2)
print(arr6)

[21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67
 69 71 73 75 77 79]


In [330]:
#08. Write a NumPy program to generate an array of 15 random numbers from 10 to 40.

arr7 = np.arange(10,40)
print(arr7)
n = np.random.randint(10,40,15)
print(n)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39]
[18 18 21 15 33 19 32 16 18 21 23 15 31 37 33]


In [331]:
#09.Write a NumPy program to generate an array of 10 random numbers from 30 to 50.

arr8 = np.arange(30,50)
print(arr8)
n = np.random.randint(30,50,10)
print(n)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[45 46 36 33 30 41 41 34 33 48]


In [332]:
#10.Write a NumPy program to generate an array of 20 random numbers from 50 to 90.

arr9 = np.arange(50,90)
print(arr9)
n = np.random.randint(50,90,20)
print(n)

[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89]
[84 84 69 52 62 81 68 57 50 65 77 66 86 85 58 78 54 56 50 66]


In [333]:
#11.Create any two arrays & perform various mathematical operations.
#i.e. Addition, Substraction, Multiplication, Divide.

arr10 = np.array([10,20,30,40])
arr11 = np.array([11,22,33,44])
print(arr10)
print(arr11)
print(arr10 + arr11)
print(arr10 - arr11)
print(arr10 * arr11)
print(arr10 / arr11)

[10 20 30 40]
[11 22 33 44]
[21 42 63 84]
[-1 -2 -3 -4]
[ 110  440  990 1760]
[0.90909091 0.90909091 0.90909091 0.90909091]


In [334]:
#12.Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21.

arr12 = np.arange(10,22)
print(arr12)
n = arr12
n = n.reshape([4,3])
print(n)

[10 11 12 13 14 15 16 17 18 19 20 21]
[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]]


In [335]:
#13.Write a NumPy program to create a 3x3 identity matrix, i.e. the diagonal  elements are 1, the rest are 0.

arr13 = np.array([1,0,0,0,1,0,0,0,1])
print(arr13)
n = arr13
n= n.reshape([3,3])
print(n)

[1 0 0 0 1 0 0 0 1]
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [336]:
#14.Write a NumPy program to find the number of rows and columns in a given matrix. 

arr14 = np.arange(10,22)
n = arr14
n = n.reshape([4,3])
print(n)
print(n.shape)

[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]]
(4, 3)


In [337]:
#15.Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

arr15 = np.array([1,0,0,0,0,0,2,0,0,0,0,0,3,0,0,0,0,0,4,0,0,0,0,0,5])
n = arr15
n = n.reshape([5,5])
print(n)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [338]:
#16.Write a NumPy program to create a 3x3x3 array filled with arbitrary values.

n = np.random.random(9)
n = n.reshape([3,3])
print(n)

[[0.93146391 0.06308829 0.65318474]
 [0.9653588  0.8882007  0.91249202]
 [0.04098349 0.12174729 0.08237065]]


In [339]:
#17.Write a NumPy program to create a 2x3x4 array filled with arbitrary values.

n = np.random.rand(2*3*4)
n = n.reshape([2,3,4])
print(n)

[[[0.08779945 0.13655132 0.73247468 0.92368089]
  [0.42855788 0.82271321 0.7588517  0.76464524]
  [0.9503041  0.9958528  0.29588464 0.92022555]]

 [[0.79751297 0.46923513 0.27473532 0.07741258]
  [0.62581224 0.53933324 0.42069833 0.94956152]
  [0.87070645 0.6368452  0.39912039 0.03556691]]]


In [340]:
#18.Write a NumPy program to convert a list of numeric values into a one- dimensional NumPy array.

x = [10,20,30,40,50]
arr16 = np.array(x)
print(arr16)

[10 20 30 40 50]


In [341]:
#19.Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

arr17 = np.arange(2,11)
n = arr17
n = n.reshape([3,3])
print(n)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [342]:
#20.Write a NumPy program to create an array with values ranging from 12 to 38.

arr18 = np.arange(12,38)
print(arr18)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [343]:
#21.Write a NumPy program to reverse an array (the first element becomes the last).

arr19 = np.arange(1,6)
print(arr19)
arr19 = arr19[::-1]
print(arr19)

[1 2 3 4 5]
[5 4 3 2 1]


In [344]:
#22.Write a NumPy program to convert an data type into to a floating type.

arr20 = np.array([10,20,30,40,50])
print(arr20)
print(f"Dtype = {arr20.dtype}")
arr20 = np.array([10,20,30,40,50],dtype = np.float16)
print(arr20)
print(f"Dtype = {arr20.dtype}")

[10 20 30 40 50]
Dtype = int64
[10. 20. 30. 40. 50.]
Dtype = float16


In [345]:
#23.Write a NumPy program to convert a list array.

x = [10,20,30,40,50]
print(x)
arr21 = np.array(x)
print(arr21)

[10, 20, 30, 40, 50]
[10 20 30 40 50]


In [346]:
#24.Write a NumPy program to get the element-wise remainder of an array of division.

arr22 = np.array([10,20,30,40,50])
print(arr22)
n = np.remainder(arr21,30)
print(n)

[10 20 30 40 50]
[10 20  0 10 20]


In [347]:
#25.Write a NumPy program to get the element-wise remainder of an array of numbers from 20 to 50 which are divisible by 3.

arr23 = np.arange(20,50)
print(arr23)
n = arr23[arr23 % 3 == 0]
print(n)
n = np.remainder(n,3)
print(n)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49]
[21 24 27 30 33 36 39 42 45 48]
[0 0 0 0 0 0 0 0 0 0]
